apiVersion: apps/v1
kind: Deployment
metadata:
  name: mekno-api-deployment
  labels: 
    app: meknoApi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meknoApi
  template:
    metadata:
      labels:
        app: meknoApi
    spec:
      containers:
      - name: mekno-microservice
        image: jomadotio/mekno-api:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mekno-api-service
spec:
  selector:
    app: meknoApi
  ports:
  - name: http-default
    protocol: TCP
    targetPort: 5000
    port: 5000
